apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mangos

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - persistentvolumes.yaml
  - mysql-statefulset.yaml
  - realmd-deployment.yaml
  - mangosd-deployment.yaml

commonLabels:
  app.kubernetes.io/name: mangos-wotlk
  app.kubernetes.io/instance: mangos-production

images:
  - name: mangos-wotlk
    newTag: latest
